[package]
name = "fr-pmx-input-setup"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["tokio"] }
itertools = "0.13.0"
prost = "0.13.1"
tokio = { version = "1.39.2", features = ["full"] }
tonic = "0.12.1"

[build-dependencies]
tonic-build = "0.12.1"
